### ISSUE TITLE
Pleroma user is getting a crash related to scopes after OAuth authenticating

### ISSUE THREAD

**Issue by jfmcbrayer** [halcy/Mastodon.py#144]
This is the traceback from brutaldon, using mastodon.py 1.3.1. Clipped to remove stuff that only pertains to brutaldon.

```
[Mon Aug 27 08:56:20.121179 2018] [wsgi:error] [pid 3287:tid 140234804758272] [remote 164.132.54.
61:48916]   File "/var/www/brutaldon.online/brutaldon/views.py", line 216, in oauth_callback
[Mon Aug 27 08:56:20.121186 2018] [wsgi:error] [pid 3287:tid 140234804758272] [remote 164.132.54.
61:48916]     redirect_uri=redirect_uri)
[Mon Aug 27 08:56:20.121194 2018] [wsgi:error] [pid 3287:tid 140234804758272] [remote 164.132.54.
61:48916]   File "/var/www/brutaldon.online/.venv/lib/python3.6/site-packages/mastodon/Mastodon.py", line 433, in log_in
[Mon Aug 27 08:56:20.121202 2018] [wsgi:error] [pid 3287:tid 140234804758272] [remote 164.132.54.
61:48916]     'Granted scopes "' + " ".join(received_scopes) + '" do not contain all of the requested scopes "' + " ".join(scopes) + '".')
[Mon Aug 27 08:56:20.121214 2018] [wsgi:error] [pid 3287:tid 140234804758272] [remote 164.132.54.61:48916] mastodon.Mastodon.MastodonAPIError: Granted scopes "read write follow read:accounts read:blocks read:favourites read:filters read:follows read:lists read:mutes read:notifications read:reports read:search read:statuses write:accounts write:blocks write:favourites write:filters write:follows write:lists write:media write:mutes write:notifications write:reports write:statuses read:blocks read:follows read:mutes write:blocks write:follows write:mutes" do not contain all of the requested scopes "read write follow push".
```

Looks like it's barfing over not getting 'push' scope. Brutaldon doesn't explicitly request particular scopes. But it doesn't currently use push scope, so I could work around by explicitly requesting only read write follow... but the defaults should work unless there's a good reason for them not to.

Thanks!

**Comment by halcy** [comment]
Hm.

The last fix change it so that we request scopes and get MORE than we need, we don't complain. This, on the other hand, would be an actual problem: If we request push, but don't get push, that _is_ an error and potential problem.

I think the correct thing here to do for brutaldon would be to in fact not request push scopes - essentially, what's going on currently is that (because the default is to request read, write and push), and since mastodon.py has no way to know that you weren't going to use those push scopes, it lets you know "hey! something went wrong! the server doesn't want to let you do this thing you are trying to do!". 

For mastodon.py, I wonder if we should just not request push scopes by default - I doubt many people are actually using them currently anyways.

**Comment by jfmcbrayer** [comment]
I'll fix brutaldon, then. I agree that not getting a scope that you wanted is an actual error.
