### ISSUE TITLE
sensitive = False still results in media being marked sensitive

### ISSUE THREAD

**Issue by halcy** [halcy/Mastodon.py#20]

**Comment by wxcafe** [comment]
This is because the mastodon API considers that if a parameter named sensitive is present, then the media is sensitive. The wording in the doc is ambiguous
<img width="600" alt="screen shot 2017-04-05 at 13 24 22" src="https://cloud.githubusercontent.com/assets/3009327/24703363/36b55946-1a03-11e7-82eb-8eabfa38a288.png">
