### ISSUE TITLE
undocumented dodgy-looking hashlib magic

### ISSUE THREAD

**Issue by marnanel** [halcy/Mastodon.py#210]
https://github.com/halcy/Mastodon.py/blob/995de2c6f948035732e6e6658ca2a605796d6e90/mastodon/Mastodon.py#L3215-L3221

What on earth is going on here? Could you at least comment it?

**Comment by halcy** [comment]
It's code that prevents people from using this library with certain instances unmodified, hashed because plaintext blocklists is just asking for trouble. It's documented to some extent in the actual docs, but you're absolutely right, there should be a comment here, otherwise it just looks weird. I'll add one when I get around to the 3.1 maint, probably this weekend.
