### ISSUE TITLE
Make AttribAccessDict hashable

### ISSUE THREAD

**Issue by allo-** [halcy/Mastodon.py#211]
An AttribAccessDict is unhashable, so you cannot put into a `set`.

Example:
When you want to collect a list of users from a set of lists, then it would be useful to add the user dicts to a set, so you do not need to filter for duplicates. Currently you get the error:

    TypeError: unhashable type: 'AttribAccessDict'

I think for every ressource that has an unique ID, the id could be used to implement a `__hash__` function, maybe like this:

    def __hash__(self):
        return str("User:" + str(self.id)

**Comment by halcy** [comment]
I'm not sure that this is reasonable. I've thought about this in the context of comparing things / object in list type tests, and here's why it is not currently done this way:

The id _does_ identify an object, but it can be the same object with different properties - i.e. the same user but user has since changed their name, or with more posts, whatever. Current unit tests are written assuming equality means all fields equal, and python requires (as far as I know) that if two objects has the same hash value they must also be equal. While it would be possible to make equality testing hit only the ID (where present) too, that would make equality on these objects mean something that's probably surprising to people who've used python a bunch, so I'm not sure it's a good idea.

I'm absolutely open to being convinced that it actually is a good idea (or that having hash and eq do different things here is and that it won't break anything terribly) and that most people totally expect this behavior, but right now, I think it is not.

**Comment by allo-** [comment]
I see the problem.
I thought about just using the ID, to avoid splitting one user object into two to make it more robust, but on the other hand there are good use cases to distinguish them from each other.

My use case was to find all users, that are in no list, so I wanted to substract `set(list_users)` from `set(followings)` for each list.

I was a bit disappointed, that you cannot do `set([user1, user2], key=lambda user: user.id)`, what would be a pythonic way to solve the problem similar to `sort`.

**Comment by halcy** [comment]
yeah, I've had similar problems, but I've not yet thought of a nice way to do this I think. That last thing would actually be fantastic, if python let you do it.

**Comment by allo-** [comment]
I looked around a bit and one advice is to use a dict with the IDs as keys instead of a set. This allows for fast insert and merge, but is less comfortable for intersection/difference operations.

So the best way would probably be something like this:

    users_dict = {}
    for user in users:
        users_dict[user.id] = user
    unique_users = users_dict.values() # a list without duplicates
    user_id_set = set(users_dict.keys())
    # Do some set operations
    result_users = [users_dict[user_id] for user_id in user_id_set]

**Comment by arittner** [comment]
Hello @allo- 

The only generic way I see is to allow an own JSON hook callback to create own dict objects instead of `AttribAccessDict`. But this is a very special solution, and I'm not sure to add this a functionality to Mastodon.py. 

This means, we enhance the constructor to receive own hooks to create custom wrapper dicts. The custom dict *must* be a subclass from `AttribAccessDict` and can implement, what the caller want. 

Please tell us, how important this is for you. I mark it as enhancement.

**Comment by allo-** [comment]
> Please tell us, how important this is for you. I mark it as enhancement.

Given that it's a bug from 2020 and I am working with the script since two years, not too important. I even had to lookup which script requires it.

On the other hand, a comment in the script tells me, that I wanted to use a `set()` because `.fetch()` and `.fetch_remaining()` can overlap when retrieving follower lists, what may be a bug or at least unwanted behavior.

The relevant code snippet is

```
following = mastodon.account_following(user_dict.id)
following += mastodon.fetch_remaining(following)
#following = set(following) # does not work
following_ids = set([user.id for user in following])
```

**Comment by arittner** [comment]
Ok, thanks for your answer. The question of *how* the `AttribAccessDict` should be hashable is something Mastodon.py cannot decide. Even if there was no `AttribAccessDict` at all, the Python `dict` would not be hashable either. So your example would not work with `dict` either.

Furthermore, it is unclear which we would have to choose. Hash by Key or Hash by Key/Value?

So either:

~~~python
    def __hash__(self):
        return hash(frozenset(self))
~~~

or

~~~python
class Hashabledict(dict):
    def __hash__(self):
        return hash((frozenset(self), frozenset(self.itervalues())))
~~~

and if you look around in Stack overflow, you'll find some more generic solutions:

~~~python
def make_hash(o):

  """
  Makes a hash from a dictionary, list, tuple or set to any level, that contains
  only other hashable types (including any lists, tuples, sets, and
  dictionaries).
  """

  if isinstance(o, (set, tuple, list)):

    return tuple([make_hash(e) for e in o])    

  elif not isinstance(o, dict):

    return hash(o)

  new_o = copy.deepcopy(o)
  for k, v in new_o.items():
    new_o[k] = make_hash(v)

  return hash(tuple(frozenset(sorted(new_o.items()))))
~~~

The third implementation would be the safe variant. But all variants would not fulfill the expectation to get an aggregation on "id" (because this is, what you want). We can't implement that in Mastodon.py then as well. The side effects would be too huge and would surprise all users (and would actually be a bug).

Therefore, I wanted to give the possibility that one can give Mastodon.py a factory function which can pass an own implementation of `AttribAccessDict`. The caller can then implement his special version and knows what effects this can have.

Anyway, your idea to use the hash function to aggregate only over `id` values is maybe not a good smelling solution, because it's against the idea about hashing in `dict` and `set`.

**Comment by allo-** [comment]
If hashing or something else (I guess python does not allow to use other methods), I would expect `set()` to be a method to eleminate exact duplicates in a list. That the object is in fact a dictionary does not have semantic meaning for the API, but is a technical detail.

The user wants to work with an object which, e.g., represents a User or a Toot. If it is a dictionary or some other data structure should not be (too) relevant. On the other hand, it is relevant to test for equality, create sets, and maybe even have an ordering relation which can be used for data structures like trees.

In my use-case using `.id` is fine, but in general one would want to distinguish between two User dictionaries with, e.g., different display names for the same user, so the hash needs to be more general.

**Comment by arittner** [comment]
But it's relevant, because a dict is a bunch of attributes without a contextual meaning. Only your knowledge and applied functionality adds a context to some of the attributes. E.g. the 'id'. But maybe it could be the name (see tags) or its unknown (see bookmarks) or maybe your decision is to use the account identifier instead of the id.

And here the Mastodon.py cannot help or define something generic. The Mastodon.py API wrapper is a low level API. This means you get a 1:1 access to the API with some helper methods to avoid boilerplate implementations (eg, token access, pagination support, streaming handling,...) but the wrapper don't know the entities. For Mastodon.py all responses are DTO (data transfer objects). Only very few certain attributes are handled in a special way to solve technical difficulties.

It's in the responsibility of the user to implement the high level functionality on top of the calls to Mastodon.py. 

However, I guess a factory function to wrap an custom dict around the respond objects will help you, to do it on a nice way. :)

**Comment by halcy** [comment]
closing as wontfix / out of scope, I guess
