### ISSUE TITLE
stream exit() does not work

### ISSUE THREAD

**Issue by Shura0** [halcy/Mastodon.py#212]
My code is:
```

        m = Mastodon(
            access_token=u.get('token'),
            api_base_url='https://' + host
        )
        listener = MyListener(mid)
        stream=m.stream_user(listener, run_async=True, reconnect_async=True)
```

Later I try to close the connection by calling
stream.close()
And I got:
```
 File "masto.py", line 154, in <module>
    stream.close()
  File "/home/shura/projects/megagate/venv/lib/python3.7/site-packages/mastodon/Mastodon.py", line 3570, in close
    self.connection.close()
AttributeError: 'NoneType' object has no attribute 'close'

```

**Comment by halcy** [comment]
oops. Will have a look at this. Weird.

**Comment by Shura0** [comment]
some details.
The error appears only if I call close() before receiving first 'heartbeat'

**Comment by arittner** [comment]
Hello @Shura0 

In case of `run_asyn = True` the connection will be established in the thread. This means, the stream handler will be initialized with an `connection = None`.

Inside the thread, the stream handler tries to connect. If this is not successful, the thread sleeps a while and do a retry, if the parameter was `reconnect_async = True`.

If I understand it correctly, we have a race condition here and maybe the heartbeat can have something to do with it, but in general the problem can always occur if the first connection attempts were not successful. 

I will rewrite the `close` function so that the error does not occur. In addition, the thread must terminate when it is determined from "outside" that a connection is no longer necessary.
