### ISSUE TITLE
AttributeError : 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by tz-jason** [halcy/Mastodon.py#222]
Hi,

I wanted to start using this, but after I created a toot in my mastodon instance, it crashes when it was syncing the data as below screen prompt, I have used MastodonToTwitter which calls mastodon.py,  it seems the attributes is not matched, is this a version issue? 

```
> [20/02/2021 23:03:10] [Mastodon -> Twitter] Listening for toots…
> None
> Exception in thread Mastodon -> Twitter:
> Traceback (most recent call last):
> File "/home/mastodon/MastodonToTwitter.clone/mtt/mastodon_to_twitter.py", line 232, in run
> self.mastodon_api.stream_user(TootsListener(self), run_async=False)
> File "", line 2, in stream_user
> File "/home/mastodon/.local/lib/python3.6/site-packages/mastodon/Mastodon.py", line 102, in wrapper
> return function(self, *args, **kwargs)
> File "/home/mastodon/.local/lib/python3.6/site-packages/mastodon/Mastodon.py", line 3110, in stream_user
> return self.__stream('/api/v1/streaming/user', listener, run_async=run_async, timeout=timeout, reconnect_async=reconnect_async, reconnect_async_wait_sec=reconnect_async_wait_sec)
> File "/home/mastodon/.local/lib/python3.6/site-packages/mastodon/Mastodon.py", line 3628, in __stream
> listener.handle_stream(r)
> File "/home/mastodon/.local/lib/python3.6/site-packages/mastodon/streaming.py", line 79, in handle_stream
> self._dispatch(event)
> File "/home/mastodon/.local/lib/python3.6/site-packages/mastodon/streaming.py", line 152, in _dispatch
> handler(payload)
> File "/home/mastodon/MastodonToTwitter.clone/mtt/mastodon_to_twitter.py", line 144, in on_update
> url=toot['uri']
> File "/home/mastodon/MastodonToTwitter.clone/mtt/utils.py", line 164, in split_status
> print(match.group(1))
> AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by codl** [comment]
Linking MastodonToTwitter issue for convenience: https://github.com/AmauryCarrade/MastodonToTwitter/issues/68

And the location where it throws:
https://github.com/AmauryCarrade/MastodonToTwitter/blob/master/mtt/utils.py#L164

At a cursory glance it looks to me like an issue in MastodonToTwitter, `match` is unset if a post has no hashtags, which is checked for later but this particular leftover debug print does not check

**Comment by tz-jason** [comment]
sure, I have created a toot using a hashtag in Mastodon,  that is ok for syncing data from mastodon to twitter now, but when I create a tweet using a hashtag, there is no response for syncing data from twitter to mastodon.

**Comment by arittner** [comment]
Hello!

The error is in the utils.py and is not part of the Mastodon.py. 

The main issue, IMHO, is the expectation about hashtags in toots. The Mastodon instance converts words with a `#` symbol to tags and replaces the hashtag in the text with a URL (markup as HTML). Maybe this URL doesn't fit to the regular expression. Btw. the match.group(1) is called, without check the match. 

It's much better to read the tags-section instead of parsing the status text. Please check the [mastodon documentation](https://docs.joinmastodon.org/entities/status/), where you can find the list of `tags` and here, [a tag entity](https://docs.joinmastodon.org/entities/tag/).
