### ISSUE TITLE
Force existing post to be sensitive as admin

### ISSUE THREAD

**Issue by kaonashi696** [halcy/Mastodon.py#228]
As I say on [this post](https://zecircle.xyz/@kaonashi696/106780125292506863), I'm trying to force a post to be sensitive (as an admin), on the Pleroma API I was doing that with a POST request to [/api/v1/pleroma/admin/statuses/:id](https://docs-develop.pleroma.social/backend/development/API/admin_api/#put-apiv1pleromaadminstatusesid), how can I do that here?

**Comment by arittner** [comment]
Hello @kaonashi696 

Sorry for the late response. In the meanwhile, the mentioned post is not available anymore. This means we need more information here in this issue. Because of maintenance, I close this issue. Please feel free to re-open the issue if the problem persists, and you can provide more information. 

Thank you!
