### ISSUE TITLE
Date based search

### ISSUE THREAD

**Issue by edent** [halcy/Mastodon.py#255]
Would you be interested in adding `before_time` and `after_time` to API calls which take `max_id` and `min_id`?

While the native API doesn't explicitly support it, I found out that it is relatively simple to do.

[All Mastodon IDs are based on Snowflake](https://mastodon.social/@Gargron/109321406286622035).

So it becomes possible to calculate the IDs used around a specific date.  For example, if you wanted to retrieve all posts between 31st December 2020 and 15th January 2021:

```python
from datetime import datetime
min_id = ( int( datetime(2020,12,31,00,00).timestamp() ) << 16 ) * 1000
max_id = ( int( datetime(2021, 1,15,23,59).timestamp() ) << 16 ) * 1000
```

[I've tried it](https://mastodon.social/@Edent/109326806576291213), and it works well.

Obviously, users can calculate this themselves, but I thought this might be a handy helpful function for this library.

**Comment by halcy** [comment]
Huh, interesting. I‘m open to adding it, but I think it‘d be important to make it clear that this is a mastodon specific implementation detail (since other fedi software that implements the masto api does _not_ use these, probably). Could gate it behind a feature set like we do hometown/pleroma/misskey specific features.

**Comment by halcy** [comment]
as per matodon dev team: they're willing to commit to it as core API, so I'll just add it as regular, with a big note to Not Do That If You Want It To Work On Pleroma And Misskey And Gotosocial

**Comment by halcy** [comment]
Added
