### ISSUE TITLE
Admin role: action is outside the authorized scopes

### ISSUE THREAD

**Issue by schousda** [halcy/Mastodon.py#263]
Hello,

when i use `list = mastodon_api.admin_reports()`
i receive this error, even if the account has the admin role assigned:

`mastodon.Mastodon.MastodonAPIError: ('Mastodon API returned error', 403, 'Forbidden', 'This action is outside the authorized scopes')`

Is this a bug or do i use the command wrong?

**Comment by halcy** [comment]
Hey,

I suspect you didn't request "admin" scope when you created the app + logged in. Mastodon.py by default requests "read", "write", "follow" and "push" permissions (anything a normal user would be able to do), but not the admin scopes, because having access tokens with admin permissions when normal user would suffice is dangerous. Try adding

scopes = ['read', 'write', 'follow', 'push', 'admin:read', 'admin:write'] 

to both your create_app and log_in calls (or oauth flow), then it should work.

docs: https://mastodonpy.readthedocs.io/en/stable/#moderation-api

**Comment by schousda** [comment]
Hello,
in fact the admin scopes were inactive in the app preferences. I activated them now.
But how do i connect with the correct scope. The Mastodon connection does not accept a parameter for scope. I didn't find anything about that in dhe docs. Only, for the login with username and password there seem to be scopes as parameter.

This is how i connect:
```
mastodon_api = Mastodon(
        api_base_url = 'mastodon.social',
        client_id = 'app_id',
        client_secret = 'app_secret',
        access_token = 'app_token',
        )

```

**Comment by schousda** [comment]
OK, my fault.
I forgot to regenerate the access token.
Thanks for the advise to the scope.
