### ISSUE TITLE
Drop support for Python < 3.7

### ISSUE THREAD

**Issue by pauloxnet** [halcy/Mastodon.py#302]
To help people contributing it would be helpful to drop support for EOL version of Python.

**Comment by halcy** [comment]
Hey, I  currently try to support 3.7 and above, but try not to break 3.x generally. If you want to submit a patch and there's a good reason to use some feature that isn't available before 3.7, then it is what it is for people on 3.6 and below, but otherwise, since this is a library, I'd prefer to not make decisions about what to upgrade when for anyone upstream.
