### ISSUE TITLE
Get the accounts of people boosted/facorite a toot?

### ISSUE THREAD

**Issue by TravelTrader** [halcy/Mastodon.py#321]
I was searching a lot through the documentation and I hope this is the right place to ask:

I want to loop through my toots and for each loop I would like an array of the accounts that boosted it and an array with the favorites.
Not only the number of how many of each.

Is that possible?
If not with this library, could you give me some starting support of how to do it with requests?

Thank you already.

**Comment by TravelTrader** [comment]
Thank you very much.

**Comment by TravelTrader** [comment]
Using .timeline() with 'home' and no or high limit gets only 40 statuses.

How can I get older toots?
Or can I ask for only my own toots (not home or local) to get at least 40 of my own backwards?

I'm sorry I couldn't solve it for my own.

**Comment by arittner** [comment]
I think it's important to mention, that the home timeline will never return more than 400, e.g 10 pages with 40, messages (for default mastodon instances). This is a hard coded limit to the internal cache, because all home timeline messages are cached in RAM.

It's possible to read more over the profile timeline. But this timeline doesn't provide all messages, like the home timeline.

**Comment by TravelTrader** [comment]
> It's possible to read more over the profile timeline. But this timeline doesn't provide all messages, like the home timeline.

I won't need more than 400 but I'd prefer using the profile timeline because I do only need my own toots.

Is it possible to get a `mastodon.timeline_profile()` in any way?

**Comment by halcy** [comment]
You’ll want https://mastodonpy.readthedocs.io/en/1.8.0/06_accounts.html#mastodon.Mastodon.account_statuses

**Comment by TravelTrader** [comment]
Thank you very much, @codl and @arittner!
