### ISSUE TITLE
Remote media upload?

### ISSUE THREAD

**Issue by edent** [halcy/Mastodon.py#324]
Is there any way to upload media from a remote source?

For example

```
media = mastodon.media_post("https://placekitten.com/200", mime_type="image/jpeg", description="Some alt text.")
```

**Comment by andypiper** [comment]
I guess you could download the media yourself and upload it; or, add a helper function to Mastodon.py that does this when provided with a URL.

The [Mastodon API for media upload](https://docs.joinmastodon.org/methods/media/#v2) requires a file object (it was fairly close to the Twitter v1.1 API, which also expected a file upload). I can imagine that there could be security issues with "sideloading" images from another server to a Mastodon instance, but that's a whole discussion for the core API rather than for this Python wrapper.

**Comment by halcy** [comment]
I think this is out of scope for Mastodon.py - if you want to upload an image from some URL, you can download it with requests and then upload it as usual, potentially via bytesIO. Something like:

resp = requests.get("http://example.com/image.jpg")
f = BytesIO(resp.content) 
mastodon.media_post(f)

or similar should work.
