### ISSUE TITLE
How to get configured character limit of Mastodon instance

### ISSUE THREAD

**Issue by jeancf** [halcy/Mastodon.py#352]
In trying to deal with `mastodon.errors.MastodonAPIError: ('Mastodon API returned error', 422, 'Unprocessable Entity', 'Validation failed: Text character limit of 500 exceeded')` I did not find a way to obtain the configured character limit of the Mastodon instance.

The `GET /api/v2/instance` method of the Mastodon API returns a JSON object including a `statuses` key with `max_characters`:
```
"statuses": {
      "max_characters": 500,
      "max_media_attachments": 4,
      "characters_reserved_per_url": 23
    }
```

but the instance dict of Mastodon.py does not include it. Would it be possible to add it?

**Comment by halcy** [comment]
Hi! v2 instance API is WIP currently, and the next release will have it, though I am currently busy with other projects, so it'll be a bit before I can get back to that. I've also considered adding a character counting helper that would help with that, but that's after that, even.

That said: The v1 API that mastodon.py fetches current *should* include that. See, for example: 

https://[icosahedron.website/api/v1/instance](https://icosahedron.website/api/v1/instance)

Under configuration.statuses, there is the information you'd want. Though also, only for recent versions, not sure at which it starts. Some software and patches will have exposed it as part of nodeinfo instead. It is a bit of a mess, which I would like to try to abstract away for this specific use case, which is why see above.

What instance are you trying to get that information from?

**Comment by edel79** [comment]
Hello,
I personnaly use these two instances :
- techhub.social
- piaille.fr

These two instances give the character limit here, using the url provided :

      "statuses":{
         "max_characters":1000,
         "max_media_attachments":4,
         "characters_reserved_per_url":23
      },

**Comment by jeancf** [comment]
I wasn't aware of the v1 and v2 distinction of the API.

> What instance are you trying to get that information from?

I am interested in getting `max_characters` from any instance (this is for integration in a bot that can run anywhere).

> The v1 API that mastodon.py fetches current should include that

Are you saying that that a call to `Mastodon.instance()` returns the contents of the JSON object returned by `api/v1/instance`?. [The documentation for the Instance Dict](https://mastodonpy.readthedocs.io/en/stable/02_return_values.html?highlight=instance#instance-dicts) looks more limited and does not include `max_characters`.

If not, I can fetch the data from `api/v1/instance` directly but it would be nice to have it through Mastodon.py.

Thanks.

**Comment by halcy** [comment]
It does return that! The documentation is out of date somewhat - earlier versions of Mastodon did not include the "configuration" part. I am trying to fix all of that, but I've been bogged down somewhat. The next version will have much better and more up to date (and also more easily updateable) documentation.

You should be able to just call mastodon.instance().configuration.statuses to get the status info - *if* the instance is new enough. If you do that, probably wrap it in a try -> except statement and assume that if it fails, value is masto default of 500.

**Comment by halcy** [comment]
closing resolved
