### ISSUE TITLE
[Question] scheduling posts and replies

### ISSUE THREAD

**Issue by zcutlip** [halcy/Mastodon.py#370]
Hi there; thanks for making Mastodon.py! It's been really easy to use for my project. Apologies for opening an issue just to ask questions.

I'm trying to figure out how to schedule posts and replies (i.e. threads), and I have a few questions

- It isn't clear from the documentation but is the `scheduled_at` date time object expected to be in UTC time? Or can I just do like `datetime.now() + time delta(minutes=6)`?
- when I schedule a post, I get back what appears to be a nonsense status ID, like 66359. Since this low number actually corresponds to existing posts on the instance, it obviously can't be used to post a thread reply
  - Is there a way to schedule a post plus a series of replies at once?

**Comment by halcy** [comment]
Hi!

no problem, this is a reasonable use of the bug tracker imo.

1) the latter will work, Mastodon.py is timezone aware and will convert to the correct representation to send to the server (utc, iso formatted string) internally. 

2) you get an id that you can use to e.g. unschedule the status, but it’s not the final status id, which I believe is only assigned when the status is creates. I don’t think scheduling reply chains is supported currently on masto side, but you could ask the masto devs about it. Otherwise you’d have to do your scheduling locally yourself.

**Comment by zcutlip** [comment]
Okay, thank you for the clarification on both!
